name: 'Android MissingTranslation Lint'
description: 'Android MissingTranslation Lint'

runs:
  using: "composite"
  steps:
    - name: Check MissingTranslation Lint
      shell: bash
      continue-on-error: true # 미번역 문구가 없으면 xmlstarlet 필터링 작업에서 실패
      run: |
        ./gradlew :app:updateLintBaseline
        
        # MissingTranslation Lint 필터링
        xmlstarlet sel \
          -t -m "//issue[@id='MissingTranslation']" \
          -v "@message" -n ./lint/lint-baseline.xml \
        | sed 's/^/• /' > ./lint/message.text

    - name: Set Result
      shell: bash
      run: |
        # 미번역 문구가 있는 경우 exit 1, 없는 경우 exit 0
        [ -s ./lint/message.text ] && exit 1 || exit 0
