name: "Calculate Distribution Version"
description: "Calculate Next Distribution Version"

outputs:
  next_year:
    description: "다음 정기배포 년도 버전"
    value: ${{ steps.calc-next-version.outputs.next_year }}
  next_week:
    description: "다음 정기배포 주차 버전"
    value: ${{ steps.calc-next-version.outputs.next_week }}
  next_hotfix:
    description: "다음 정기배포 핫픽스 버전"
    value: ${{ steps.calc-next-version.outputs.next_hotfix }}

runs:
  using: "composite"
  steps:
    - name: Calc Next Version
      id: calc-next-version
      shell: bash
      run: |
        # 다음 정기배포 버전 정보
        current_year=$(TZ="Asia/Seoul" date +'%y')
        current_week=$(TZ="Asia/Seoul" date +'%V')

        # 다음주 정기배포를 + 1
        next_year=$current_year
        next_week=$(($current_week + 1))
        next_hotfix=00

        # 주차 번호가 52를 초과하는 경우 연도를 증가시키고 주차를 계산해요
        if [ $next_week -gt 52 ]; then
            next_year=$((next_year + 1))
            next_week=$((next_week - 52))
        fi

        echo "next_year=$next_year" >> $GITHUB_OUTPUT
        echo "next_week=$next_week" >> $GITHUB_OUTPUT
        echo "next_hotfix=$next_hotfix" >> $GITHUB_OUTPUT
