name: "[CD] Generate Release Notes"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
            
      - name: Get App Version
        id: get-app-version
        uses: ./.github/actions/get-app-version

      - name: Create Release
        run: |
          tag_name=${{ steps.get-app-version.outputs.version_code }}
          name=${{ steps.get-app-version.outputs.version_name }}

          RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/kts6056/droidknights-2024-github-actions/releases \
            -d '{"tag_name":"$tag_name","target_commitish":"main","name":"$name","generate_release_notes":true}' \
            -w "\n%{http_code}" -o -)

          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
          RESPONSE_CODE=$(echo "$RESPONSE" | tail -n 1)

          echo "Response Code: $RESPONSE_CODE"
          echo "Response Body: $RESPONSE_BODY"

          if [ "$RESPONSE_CODE" -lt 200 ] || [ "$RESPONSE_CODE" -gt 299 ]; then
            exit 1
          fi
